import { Geist, Geist_Mono,Mogra } from "next/font/google";
import "@/app/globals.css";
import {SessionProvider} from "next-auth/react";
import { auth } from "@/auth";

const mogra = Mogra({
  weight:"400",
  subsets:["latin"],
  variable:"--font-mogra"
})
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth()
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${mogra.variable} antialiased `}
      >
        <SessionProvider session={session}>
        {children}
        </SessionProvider>
      
      </body>
    </html>
  );
}